### ISSUE TITLE
Markers is not rendering

### ISSUE THREAD

**Issue by Walkplay** [freyastreamlit/streamlit-lightweight-charts#23]
![image](https://user-images.githubusercontent.com/28632912/230779782-e0a72c2c-83a6-4ded-84e4-17c5a73c5fe5.png)
I'm just paste example code in my app and I can't see markers rendering. Btw in your demo i can't see them either

I tried to change marker object layout, since I saw that in official TradeView example it differs from yours, but it didn't workout((
Unfortunately, I have no idea how to fix this((

**Comment by freyastreamlit** [comment]
Hello Walkplay

Thanks for the feedback - appreciated
FIXED - It was a build issue not updating (committing) the React app wrapper build

- https://freyastreamlit-streamlit-ligh-examplesoverlaidareaschart-3pg5tr.streamlit.app/

If you: `python -m pip install streamlit-lightweight-charts==0.7.19` should fix your local

Let me know...

**Comment by Walkplay** [comment]
Fixed. Thank you very much!
