### ISSUE TITLE
Text is not appearing at the specified hour and minute

### ISSUE THREAD

**Issue by NijanJ** [freyastreamlit/streamlit-lightweight-charts#26]
When using a 5-minute chart, the text is not appearing at the specified hour and minute, but rather at the beginning or end of the day. Additionally, when zooming in, the text disappears. How to resolve this issue?

**Comment by NijanJ** [comment]
.

**Comment by freyastreamlit** [comment]
Hi @NijanJ 

If you are referring to the text in the timescale (horizontal scale), are you setting the `time` as UTCtimestamp:

- https://tradingview.github.io/lightweight-charts/docs/api#time
- https://tradingview.github.io/lightweight-charts/docs/api#utctimestamp

Go to https://tradingview.github.io/lightweight-charts/docs/api and on left menu (under Interfaces) choose the type of chart you are creating, and the API documentation is very thorough.. 

Let me knwo

Best,

Joe Rosa
