### ISSUE TITLE
 Excessive Gap Between Text and Candlestick When Plotted

### ISSUE THREAD

**Issue by NijanJ** [freyastreamlit/streamlit-lightweight-charts#31]
I am encountering an issue where there is a significant gap between the text and the candlestick when I attempt to plot text above or below the candlestick. The resulting gap is larger than expected and disrupts the visualization.

`            {
                "time": candles[820]["time"],
                "position": 'aboveBar',
                "color": 'rgba(255, 192, 0, 1)',
                # "shape": 'arrowUp',
                "text": 'L',
                "size": 8
            }`
            
            
Expected Behavior:
I expect the text labels to be positioned near the candlestick, with a minimal or customizable gap between them.

**Comment by itpmngt** [comment]
Hi @NijanJ 

Are you referring to `markers`?
Could you please upload a screenshot of an example?

Best,

Joe
