### ISSUE TITLE
Embed moving average as part of candlestick chart and ability to see ohlc data as we hover over each candlestick

### ISSUE THREAD

**Issue by baluinfo86** [freyastreamlit/streamlit-lightweight-charts#34]
Wanted to check if there is an option to see daily ohlc data values on candlestick as we hover over.
Also wanted to check if we can embed moving average as part of candlestick chart.

![image](https://github.com/freyastreamlit/streamlit-lightweight-charts/assets/58189368/8b629246-8524-48b5-a6fd-ca0ee9df1bf6)

**Comment by freyastreamlit** [comment]
Hi @baluinfo86 

Regarding 'legends' and 'tooltips' - nope 👎 -. There are some limitations in the bi-directional communication between streamlit and the react-component - although I saw a few workarounds, I am considering some improvements 

Regarding moving averages - yes 👍 - it is meant for that. just add mutiple dicts to the data series - eg:

```
seriesMACDchart = [
    {
        "type": 'Line',
        "data": macd_fast,
        "options": {
            "color": 'blue',
            "lineWidth": 2
        }
    },
    {
        "type": 'Line',
        "data": macd_slow,
        "options": {
            "color": 'green',
            "lineWidth": 2
        }
    },
    {
        "type": 'Histogram',
        "data": macd_hist,
        "options": {
            "color": 'red',
            "lineWidth": 1
        }
    }
]
```

**Comment by baluinfo86** [comment]
great, thanks a lot, able to figure out what was the issue, seems converted ema dict was expecting column name as value, when I renamed them, able to embed the ema on top of the candlestick chart. Thanks again

![image](https://github.com/freyastreamlit/streamlit-lightweight-charts/assets/58189368/2a2c373c-928c-4877-a586-f7413e8d1490)
