### ISSUE TITLE
Is it possible to render live candle using live streamingtick data?

### ISSUE THREAD

**Issue by mtech2008** [freyastreamlit/streamlit-lightweight-charts#35]
Just stubled across your package. I am yet to give it a try, but it's looking intresting. I have doubt about rendering live tick by tick data. Is it possible to render live candle using live streaming tick data with this package?

**Comment by freyastreamlit** [comment]
Hi @mtech2008 

Well, streamlit is not conceived for that. I know some people try a dashboard type like
https://blog.streamlit.io/how-to-build-a-real-time-live-dashboard-with-streamlit/
It is a continuous page refresh that gives the feeling that it is live

But that is not what 'streamlit' is for, nor the 'lightweight charts` libraries, using setData or updateData the page still needs to re-render each time: https://tradingview.github.io/lightweight-charts/docs

If you are looking to setup your own live I would suggest:
https://medium.com/marcius-studio/financial-charts-for-your-application-cfcceb147786
That will use the real full-blown TV JS, and there are overlays and a community around...

Good luck on your projects
