### ISSUE TITLE
streamlit deploy error

### ISSUE THREAD

**Issue by timesavingbee** [freyastreamlit/streamlit-lightweight-charts#36]
Hello.
I tried to deploy streamlit-lightweight-charts multi pane sample, but I got an error as following.

File "/mount/src/macro/streamlit_app.py", line 2, in
from streamlit_lightweight_charts import renderLightweightCharts

Even though I added requirements.txt as following.
streamlit-lightweight-charts

Please let me know how to solve this issue.
This error happens on streamlit_lightweight_charts_ntf too.

**Comment by freyastreamlit** [comment]
@timesavingbee 

The error says that you don't have the package(s) installed on your machine
Not sure your experience with python, so lets cover possibilities:

Are you installing the 'requirements..txt' file with: `pip install -r requirements.txt`

Another possibility is that you have multiple python installs on your machine (typical for MACs) - so make sure you install for the correct version - `python --version`.
We do need python 3 - so check if you can run `python3` and if so:

`python3 -m pip install streamlit-lightweight-charts` or
`pip3 install streamlit-lightweight-charts`

And let me know which OS machine are you using

Best,

Joe

**Comment by timesavingbee** [comment]
> @timesavingbee
> 
> The error says that you don't have the package(s) installed on your machine Not sure your experience with python, so lets cover possibilities:
> 
> Are you installing the 'requirements..txt' file with: `pip install -r requirements.txt`
> 
> Another possibility is that you have multiple python installs on your machine (typical for MACs) - so make sure you install for the correct version - `python --version`. We do need python 3 - so check if you can run `python3` and if so:
> 
> `python3 -m pip install streamlit-lightweight-charts` or `pip3 install streamlit-lightweight-charts`
> 
> And let me know which OS machine are you using
> 
> Best,
> 
> Joe

You are so kind and thank you so much~!
As I am a python beginner, I didn't know how to make requirements.txt properly.
It works very well, thank you~!!!
