### ISSUE TITLE
Markers are dispeared at the same time when I zoom in.

### ISSUE THREAD

**Issue by timesavingbee** [freyastreamlit/streamlit-lightweight-charts#42]
Thank you so much for this great job.
Do you know how to solve the problem that markers are dispeared at the same time when I zoom in the screen.
I made 3 markers and I zoomed the screen to see 2 markers only.
But 2 markers were disappeared at the same time when 1 marker disappeared on the screen.
Please let me know how to solve this.

**Comment by freyastreamlit** [comment]
HI @timesavingbee 

Tricky one - but here are some suggestions to start:

Keeping in mind that this wrapper acts as a container and transfers data between python to javascript (one way)
Gathering some information could help to pinpoint the issue:

- Which devices does it happens (Mobile, Desktop, ...)?
- How are you zooming (pinching, mouse, )?
- Does streamlit reruns/refreshes each time you Zoom it?
- There is a demo on how to implement markers, it is running on the streamlit cloud:
  https://freyastreamlit-streamlit-ligh-examplesoverlaidareaschart-3pg5tr.streamlit.app/
(that should be the reference of markers behaviour - seems that zooming works fine)

Hope this helps as a starting point
