### ISSUE TITLE
Click event handling over candlestick charts

### ISSUE THREAD

**Issue by pythonbaskar** [freyastreamlit/streamlit-lightweight-charts#43]
Hello Greetings !!,
It would be of great help if there is some documentation on chart click events handling. Basically if i click a specific candle i need to print the respective data frame row. Would be of immense help in my data analysis.

Thanks.

**Comment by itpmngt** [comment]
Hello @pythonbaskar 

The 'renderLightweightCharts' returns a json object with the bar clicked

`
click_events = renderLightweightCharts([
    {
        "chart": chartMultipaneOptions[0],
        "series": seriesMultipaneChart
    }
], 'multipane')

print('onClick event', click_events)
`

There is another frozen-fork [the ntf fork](`https://github.com/freyastreamlit/streamlit-lightweight-charts-ntf`) that has an example

Hope that helps...

Best,

Joe Rosa
