### ISSUE TITLE
Is it possible to turnoff priceLine in PriceLineOptions?

### ISSUE THREAD

**Issue by xemltil** [freyastreamlit/streamlit-lightweight-charts#44]
Q1:  Is it possible to turnoff priceLine in PriceLineOptions?

Original Lightweight-Charts JSON:

export interface PriceLineOptions {
        ...
	/**
	 * Display line.
	 *
	 * @defaultValue `true`
	 */
	lineVisible: boolean;
        ...
}

Source:  https://github.com/tradingview/lightweight-charts/blob/master/src/model/price-line-options.ts

**Comment by freyastreamlit** [comment]
Hi @xemltil 

You don't have access to Javascript side of things - in Python we put together data and options and send that to Javascript, and Javascript will render:

`
renderLightweightCharts([
    {
        "chart": chartOptions,
        "series": seriesBarChart
    }
], 'bar')
`
A good place to look is https://tradingview.github.io/lightweight-charts/tutorials/how_to/inverted-price-scale 

Best,

Joe Rosa
