### ISSUE TITLE
Is it possible to make the crosshair align on multipanel display?

### ISSUE THREAD

**Issue by xemltil** [freyastreamlit/streamlit-lightweight-charts#45]
How would you enable crosshair alignment of multipane from your example?

renderLightweightCharts([
    {
        "chart": chartMultipaneOptions[0],
        "series": seriesCandlestickChart
    },
    {
        "chart": chartMultipaneOptions[1],
        "series": seriesVolumeChart
    },
    {
        "chart": chartMultipaneOptions[2],
        "series": seriesMACDchart
    }
], 'multipane')

**Comment by freyastreamlit** [comment]
Hi @xemltil 

No, but there is an old frozen fork that has a good solution - have a look:

https://github.com/freyastreamlit/streamlit-lightweight-charts-ntf

 Best,

Joe Rosa
