### ISSUE TITLE
Unable to set custom priceFormat

### ISSUE THREAD

**Issue by ghost** [freyastreamlit/streamlit-lightweight-charts#48]
Hi, can you please guide on how to set custom priceFormat. I am following the official documentation but it is not working.

https://tradingview.github.io/lightweight-charts/docs/api#priceformatterfn

**Comment by freyastreamlit** [comment]
Hi @msr-agentsmyth 

Not possible - we can't pass JavaScript functions from inside a Pythion environment - the plugin passes a JSON between both environments - we can't pass functions in a JSON.

I saw some workaround in other plugins like streamlit-AgGrid - passing text and 'eval' in JavaScript before rendering, but that s kind of complicated plus most of use-cases we will need variables from JavaScript side of things...  not sure... - let's keep it simples...

Best,

Joe Rosa
